### ISSUE TITLE
Incorrect types

### ISSUE THREAD

**Issue by robcresswell** [dominictarr/hashlru#22]
The types for this lib declare a default export; which it doesn't have (default exports are an ES6 construct)

**Comment by dominictarr** [comment]
I don't actually use types, but it exports a single function, which is my understanding is what "export default" does.  @alxolr made types PR... you two can duke it out and if something is wrong some one else make another PR.

**Comment by robcresswell** [comment]
Ha, gotcha, thanks @dominictarr
