### ISSUE TITLE
max capacity is not working

### ISSUE THREAD

**Issue by pajaydev** [dominictarr/hashlru#23]
Keeping LRU cache size as 2 and trying to do the below operation.

```javascript

cache.set("A", 1);
cache.set("B", 2);
cache.set("C", 3);

console.log(cache.has("A"))  // true
```

Ideally since the capacity of lru cache is 2, we should evict "A" it should have only "B" and "C".  In the above example, it should return `false`.

**Comment by dominictarr** [comment]
in hashlru, things are evicted when the current cache gets to 2N (as described in the readme ;)

**Comment by pajaydev** [comment]
@dominictarr  ohh okay cool. Thanks :)
